version: "3.9"
name: opifolio
services:
  opifolio:
    container_name: opifolio
    image: opisek/opifolio-v2:latest
    ports:
      - 80:3000
    volumes:
      - ./config:/app/config
      - ./posts:/app/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    user: "bun"
